(cl:defpackage my_robot2_msgs-msg
  (:use )
  (:export
   "<COUNTUNTILACTION>"
   "COUNTUNTILACTION"
   "<COUNTUNTILACTIONFEEDBACK>"
   "COUNTUNTILACTIONFEEDBACK"
   "<COUNTUNTILACTIONGOAL>"
   "COUNTUNTILACTIONGOAL"
   "<COUNTUNTILACTIONRESULT>"
   "COUNTUNTILACTIONRESULT"
   "<COUNTUNTILFEEDBACK>"
   "COUNTUNTILFEEDBACK"
   "<COUNTUNTILGOAL>"
   "COUNTUNTILGOAL"
   "<COUNTUNTILRESULT>"
   "COUNTUNTILRESULT"
  ))

