; Auto-generated. Do not edit!


(cl:in-package my_robot2_msgs-msg)


;//! \htmlinclude MoveRobotFeedback.msg.html

(cl:defclass <MoveRobotFeedback> (roslisp-msg-protocol:ros-message)
  ((current_position
    :reader current_position
    :initarg :current_position
    :type cl:integer
    :initform 0))
)

(cl:defclass MoveRobotFeedback (<MoveRobotFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveRobotFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveRobotFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_robot2_msgs-msg:<MoveRobotFeedback> is deprecated: use my_robot2_msgs-msg:MoveRobotFeedback instead.")))

(cl:ensure-generic-function 'current_position-val :lambda-list '(m))
(cl:defmethod current_position-val ((m <MoveRobotFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_robot2_msgs-msg:current_position-val is deprecated.  Use my_robot2_msgs-msg:current_position instead.")
  (current_position m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveRobotFeedback>) ostream)
  "Serializes a message object of type '<MoveRobotFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'current_position)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveRobotFeedback>) istream)
  "Deserializes a message object of type '<MoveRobotFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'current_position) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveRobotFeedback>)))
  "Returns string type for a message object of type '<MoveRobotFeedback>"
  "my_robot2_msgs/MoveRobotFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveRobotFeedback)))
  "Returns string type for a message object of type 'MoveRobotFeedback"
  "my_robot2_msgs/MoveRobotFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveRobotFeedback>)))
  "Returns md5sum for a message object of type '<MoveRobotFeedback>"
  "ce06827e612a0991667c0287cf6c3f6f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveRobotFeedback)))
  "Returns md5sum for a message object of type 'MoveRobotFeedback"
  "ce06827e612a0991667c0287cf6c3f6f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveRobotFeedback>)))
  "Returns full string definition for message of type '<MoveRobotFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int64 current_position~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveRobotFeedback)))
  "Returns full string definition for message of type 'MoveRobotFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int64 current_position~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveRobotFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveRobotFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveRobotFeedback
    (cl:cons ':current_position (current_position msg))
))
