// Generated by gencpp from file my_robot_msgs/SetLedRequest.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_SETLEDREQUEST_H
#define MY_ROBOT_MSGS_MESSAGE_SETLEDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_msgs
{
template <class ContainerAllocator>
struct SetLedRequest_
{
  typedef SetLedRequest_<ContainerAllocator> Type;

  SetLedRequest_()
    : led_number(0)
    , state(0)  {
    }
  SetLedRequest_(const ContainerAllocator& _alloc)
    : led_number(0)
    , state(0)  {
  (void)_alloc;
    }



   typedef int64_t _led_number_type;
  _led_number_type led_number;

   typedef int64_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::my_robot_msgs::SetLedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_msgs::SetLedRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetLedRequest_

typedef ::my_robot_msgs::SetLedRequest_<std::allocator<void> > SetLedRequest;

typedef boost::shared_ptr< ::my_robot_msgs::SetLedRequest > SetLedRequestPtr;
typedef boost::shared_ptr< ::my_robot_msgs::SetLedRequest const> SetLedRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_msgs::SetLedRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_msgs::SetLedRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_robot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'my_robot_msgs': ['/home/achliopa/workspace/udemy/udemy_BeginnersROSCourse/mycode/catkin_ws/src/my_robot_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::SetLedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::SetLedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::SetLedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::SetLedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::SetLedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::SetLedRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_msgs::SetLedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "279825f363a2b5cf6c217db8f57892e9";
  }

  static const char* value(const ::my_robot_msgs::SetLedRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x279825f363a2b5cfULL;
  static const uint64_t static_value2 = 0x6c217db8f57892e9ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_msgs::SetLedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_msgs/SetLedRequest";
  }

  static const char* value(const ::my_robot_msgs::SetLedRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_msgs::SetLedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 led_number\n\
int64 state\n\
";
  }

  static const char* value(const ::my_robot_msgs::SetLedRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_msgs::SetLedRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.led_number);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetLedRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_msgs::SetLedRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_msgs::SetLedRequest_<ContainerAllocator>& v)
  {
    s << indent << "led_number: ";
    Printer<int64_t>::stream(s, indent + "  ", v.led_number);
    s << indent << "state: ";
    Printer<int64_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_SETLEDREQUEST_H
